/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import domain.Korisnik;
import forms.util.FormView;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import sun.security.pkcs11.Secmod;

/**
 *
 * @author Ilija Dumanović
 */
public class Glavna extends javax.swing.JFrame {

    List<Korisnik> korisnici;
    Korisnik korisnik;

    public Glavna() {
        super("Projekat PS - Početna forma");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        jMenuBar1.setVisible(false);
        txtSifra.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnPrijava = new javax.swing.JButton();
        txtSifra = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        miKreirajAntikvitet = new javax.swing.JMenuItem();
        miPretraziAntikvitet = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        miKreirajVlasnika = new javax.swing.JMenuItem();
        miPretraziVlsanika = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miKreirajAukciju = new javax.swing.JMenuItem();
        miPretragaAukcije = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        miOpis = new javax.swing.JMenuItem();
        miOdjava = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikacija");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 80)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dobrodošli u aplikaciju!");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Da bi nastavili sa radom, molimo Vas da se prijavite:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Korisničko ime:");

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        txtUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsername.setMaximumSize(new java.awt.Dimension(80, 49));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Šifra:");
        jLabel4.setMaximumSize(new java.awt.Dimension(266, 54));
        jLabel4.setMinimumSize(new java.awt.Dimension(266, 54));

        btnPrijava.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        btnPrijava.setText("Prijavi se");
        btnPrijava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrijavaActionPerformed(evt);
            }
        });

        txtSifra.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        txtSifra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSifra.setText("jPasswordField1");
        txtSifra.setMaximumSize(new java.awt.Dimension(80, 49));
        txtSifra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSifraActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));

        jMenu2.setText("Antikvitet");

        miKreirajAntikvitet.setText("Kreiranje antikviteta");
        miKreirajAntikvitet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKreirajAntikvitetActionPerformed(evt);
            }
        });
        jMenu2.add(miKreirajAntikvitet);

        miPretraziAntikvitet.setText("Pretrazivanje antikviteta");
        miPretraziAntikvitet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretraziAntikvitetActionPerformed(evt);
            }
        });
        jMenu2.add(miPretraziAntikvitet);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Vlasnik");

        miKreirajVlasnika.setText("Kreiranje vlasnika");
        miKreirajVlasnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKreirajVlasnikaActionPerformed(evt);
            }
        });
        jMenu1.add(miKreirajVlasnika);

        miPretraziVlsanika.setText("Pretrazivanje vlasnika");
        miPretraziVlsanika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretraziVlsanikaActionPerformed(evt);
            }
        });
        jMenu1.add(miPretraziVlsanika);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Aukcija");

        miKreirajAukciju.setText("Kreiraj aukciju");
        miKreirajAukciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKreirajAukcijuActionPerformed(evt);
            }
        });
        jMenu3.add(miKreirajAukciju);

        miPretragaAukcije.setText("Pretraži aukcije");
        miPretragaAukcije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaAukcijeActionPerformed(evt);
            }
        });
        jMenu3.add(miPretragaAukcije);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Aplikacija");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        miOpis.setText("Opis");
        miOpis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOpisActionPerformed(evt);
            }
        });
        jMenu4.add(miOpis);

        miOdjava.setText("Odjava");
        miOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOdjavaActionPerformed(evt);
            }
        });
        jMenu4.add(miOdjava);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(413, 413, 413)
                .addComponent(btnPrijava, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(txtSifra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrijava)
                .addGap(86, 86, 86))
        );

        txtUsername.getAccessibleContext().setAccessibleName("");

        setSize(new java.awt.Dimension(1270, 649));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miKreirajAntikvitetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKreirajAntikvitetActionPerformed
        new KreiranjeAntikviteta(FormView.FORM_ADD_MODE).setVisible(true);
    }//GEN-LAST:event_miKreirajAntikvitetActionPerformed

    private void miKreirajVlasnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKreirajVlasnikaActionPerformed
        new KreiranjeVlasnika(FormView.FORM_ADD_MODE).setVisible(true);
    }//GEN-LAST:event_miKreirajVlasnikaActionPerformed

    private void miKreirajAukcijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKreirajAukcijuActionPerformed
        new KreiranjeAukcije(FormView.FORM_ADD_MODE).setVisible(true);
    }//GEN-LAST:event_miKreirajAukcijuActionPerformed

    private void miPretraziAntikvitetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretraziAntikvitetActionPerformed
        new PretrazivanjeAntikviteta().setVisible(true);
    }//GEN-LAST:event_miPretraziAntikvitetActionPerformed

    private void miPretraziVlsanikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretraziVlsanikaActionPerformed
        new PretrazivanjeVlasnika().setVisible(true);
    }//GEN-LAST:event_miPretraziVlsanikaActionPerformed

    private void btnPrijavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrijavaActionPerformed

        try {
            if (validacijaPodataka()) {
                korisnik = Komunikacija.getInstance().login(txtUsername.getText(), txtSifra.getText());

                JOptionPane.showMessageDialog(this, "Uspšno ste se ulogovali u aplikaciju. Možete nastaviti sa radom.", "Poruka", JOptionPane.INFORMATION_MESSAGE);
                jLabel5.setText("");
                jMenuBar1.setVisible(true);
                txtUsername.setText(korisnik.getUsername());
                txtSifra.setText("");
                txtUsername.setEditable(false);
                txtSifra.setEditable(false);
                jLabel2.setText("Ulogovan je korisnik sa imenom: " + korisnik.getIme() + " i prezimenom: " + korisnik.getPrezime() + ".");
                btnPrijava.setVisible(false);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Poruka", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_btnPrijavaActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed

    }//GEN-LAST:event_jMenu4ActionPerformed

    private void miOpisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOpisActionPerformed
        new OAplikaciji().setVisible(true);
    }//GEN-LAST:event_miOpisActionPerformed

    private void txtSifraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSifraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSifraActionPerformed

    private void miOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOdjavaActionPerformed
        int broj = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite da se odjavite sa aplikacije?", "Odjava", JOptionPane.YES_NO_OPTION);
        if (broj == 0) {
            try {
                String str = Komunikacija.getInstance().logout();
                JOptionPane.showMessageDialog(this, str);
                jMenuBar1.setVisible(false);
                jLabel2.setText("Da bi nastavili sa radom, molimo Vas da se prijavite:");
                txtUsername.setText("");
                txtSifra.setText("");
                txtUsername.setEditable(true);
                txtSifra.setEditable(true);
                btnPrijava.setVisible(true);

            } catch (Exception ex) {
                Logger.getLogger(Glavna.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_miOdjavaActionPerformed

    private void miPretragaAukcijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaAukcijeActionPerformed
        new PretrazivanjeAukcije().setVisible(true);
    }//GEN-LAST:event_miPretragaAukcijeActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            Komunikacija.getInstance().logout();
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(Glavna.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrijava;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miKreirajAntikvitet;
    private javax.swing.JMenuItem miKreirajAukciju;
    private javax.swing.JMenuItem miKreirajVlasnika;
    private javax.swing.JMenuItem miOdjava;
    private javax.swing.JMenuItem miOpis;
    private javax.swing.JMenuItem miPretragaAukcije;
    private javax.swing.JMenuItem miPretraziAntikvitet;
    private javax.swing.JMenuItem miPretraziVlsanika;
    private javax.swing.JPasswordField txtSifra;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private boolean validacijaPodataka() {
        boolean i = true;
        StringBuilder sb = new StringBuilder();
        sb.append("Neispravno unete vrednosti! Polje ");
        if (txtUsername.getText().isEmpty()) {
            sb.append("korisničko ime");
            i = false;
        }
        if (txtSifra.getText().isEmpty()) {
            if (i) {
                sb.append(" i polje šifra");
            } else {
                sb.append("šifra");
            }
            i = false;
        }
        sb.append(" ne sme biti prazno!");

        if (!i) {
            jLabel5.setText(sb.toString());
        }
        return i;
    }
}
