/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import domain.Antikvitet;
import forms.util.FormView;
import forms.util.ModelTabele;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import komunikacija.Komunikacija;
import model.AntikvitetiTableModel;
import model.VlasniciTableModel;
import model.nit.NitTabele;

/**
 *
 * @author Ilija Dumanović
 */
public class PretrazivanjeAntikviteta extends javax.swing.JFrame {

    /**
     * Creates new form PretrazivanjeAntikviteta
     */
    List<Antikvitet> antikviteti;
    List<Antikvitet> pretraga;
    String strPretraga = "";
    NitTabele n;

    public PretrazivanjeAntikviteta() {
        initComponents();
        uzmiAntikvitete();
        populateForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPretraga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAntikviteti = new javax.swing.JTable();
        btnDetalji = new javax.swing.JButton();
        btnNoviAntikvitet = new javax.swing.JButton();
        btnPretrazi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pretrazivanje antikviteta");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Antikviteti");

        jLabel2.setText("Pretraži antikvitete po nazivu:");

        tblAntikviteti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAntikviteti);

        btnDetalji.setText("Detalji o antikvitetu");
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });

        btnNoviAntikvitet.setText("Unesi novi antikvitet");
        btnNoviAntikvitet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoviAntikvitetActionPerformed(evt);
            }
        });

        btnPretrazi.setText("Pretraži");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        jButton1.setText("Osveži tabelu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNoviAntikvitet, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazi)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNoviAntikvitet)
                    .addComponent(btnDetalji))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(897, 520));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNoviAntikvitetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoviAntikvitetActionPerformed

        try {
            new KreiranjeAntikviteta(FormView.FORM_ADD_MODE).setVisible(true);
            tblAntikviteti.getSelectionModel().clearSelection();
            uzmiAntikvitete();
        } catch (Exception ex) {
            Logger.getLogger(PretrazivanjeAntikviteta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNoviAntikvitetActionPerformed

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed
        if (tblAntikviteti.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da prikaže podatke antikviteta. Molomo Vas da izaberete antikvitet pre prikazivanja detalja! ", "Poruka", JOptionPane.INFORMATION_MESSAGE);
        } else if (pretraga != null) {
            Antikvitet a = pretraga.get(tblAntikviteti.getSelectedRow());
            System.out.println("forms.PretrazivanjeAntikviteta.btnDetaljiActionPerformed(), antikvitet za prikaz: " + a);
            new KreiranjeAntikviteta(FormView.FORM_VIEW_MODE, a, this,null);

        } else {
            uzmiAntikvitete();
            Antikvitet a = antikviteti.get(tblAntikviteti.getSelectedRow());
            System.out.println("forms.PretrazivanjeAntikviteta.btnDetaljiActionPerformed(), antikvitet za prikaz: " + a);
            new KreiranjeAntikviteta(FormView.FORM_VIEW_MODE, a, this,null);
            tblAntikviteti.getSelectionModel().clearSelection();

        }
    }//GEN-LAST:event_btnDetaljiActionPerformed

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        strPretraga = txtPretraga.getText().toLowerCase();
        if (!strPretraga.isEmpty()) {
            pretragaAntikviteta();
            if (pretraga.size() == 0) {
                JOptionPane.showMessageDialog(this, "Sistem ne može da nađe antikvitet po zadatoj vrednosti.Ne postoji antikvitet sa tim imenom!");
            } else if (pretraga.size() > 1) {
                tblAntikviteti.setModel(new AntikvitetiTableModel(pretraga));
                JOptionPane.showMessageDialog(this, "Sistem je pronašao više rezultata. Molimo Vas da odaberete neki od prikazanih antikviteta.");
            } else {
                tblAntikviteti.setModel(new AntikvitetiTableModel(pretraga));
                JOptionPane.showMessageDialog(this, "Sistem je našao antikvitet po zadatoj vrednosti.");
            }
            tblAntikviteti.getSelectionModel().clearSelection();
        } else {
            pretraga = null;
            JOptionPane.showMessageDialog(this, "Pre pretrage unesite karaktere za pretragu.");
        }
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pretraga = null;
        txtPretraga.setText("");
        tblAntikviteti.setModel(new AntikvitetiTableModel());
        tblAntikviteti.getSelectionModel().clearSelection();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        n.promeniSignal();
       n=null;
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton btnNoviAntikvitet;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAntikviteti;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables

    private void populateForm() {
        try {
            tblAntikviteti.setModel(new AntikvitetiTableModel());
            n = new NitTabele(tblAntikviteti, ModelTabele.ANTIKVITET_MODEL);
        } catch (Exception ex) {
            Logger.getLogger(PretrazivanjeAntikviteta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void uzmiAntikvitete() {
        try {
            antikviteti = Komunikacija.getInstance().UcitajAntikvitete();
        } catch (Exception ex) {
            Logger.getLogger(PretrazivanjeAntikviteta.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void pretragaAntikviteta() {
        uzmiAntikvitete();
        pretraga = new ArrayList<>();
        for (Antikvitet antikvitet : antikviteti) {
            if (antikvitet.getNaziv().toLowerCase().contains(strPretraga)) {
                pretraga.add(antikvitet);
            }
        }

    }
}
