/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import domain.Antikvitet;
import domain.Vlasnik;
import forms.util.FormView;
import forms.util.ModelTabele;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import model.VlasniciTableModel;
import model.nit.NitTabele;

/**
 *
 * @author Ilija Dumanović
 */
public class PretrazivanjeVlasnika extends javax.swing.JFrame {

    /**
     * Creates new form PretrazivanjeVlasnika
     */
    List<Vlasnik> vlasnici;
    List<Vlasnik> pretraga;
    String strPretraga = "";
    NitTabele n;

    public PretrazivanjeVlasnika() {
        initComponents();
        uzmiVlasnike();
        populateForm();
        tblVlasnici.getColumnModel().getColumn(0).setMinWidth(120);
        tblVlasnici.getColumnModel().getColumn(1).setMinWidth(120);
        tblVlasnici.getColumnModel().getColumn(3).setMinWidth(120);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPretraga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVlasnici = new javax.swing.JTable();
        btnDetalji = new javax.swing.JButton();
        btnNoviVlasnik = new javax.swing.JButton();
        btnPretrazi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pretrazivanje vlasnika");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Vlasnici");

        jLabel2.setText("Pretraživanje vlasnika po imenu i/ili prezimenu:");

        tblVlasnici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblVlasnici);

        btnDetalji.setText("Detalji o vlasniku");
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });

        btnNoviVlasnik.setText("Unesi novog vlasnika");
        btnNoviVlasnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoviVlasnikActionPerformed(evt);
            }
        });

        btnPretrazi.setText("Pretraži");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        jButton1.setText("Osveži tabelu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNoviVlasnik))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazi)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetalji)
                    .addComponent(btnNoviVlasnik))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(947, 441));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNoviVlasnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoviVlasnikActionPerformed
        try {
            new KreiranjeVlasnika(FormView.FORM_ADD_MODE).setVisible(true);
            tblVlasnici.getSelectionModel().clearSelection();
            uzmiVlasnike();
        } catch (Exception ex) {
            Logger.getLogger(PretrazivanjeVlasnika.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNoviVlasnikActionPerformed

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed
        if (tblVlasnici.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da prikaže podatke vlasnika. Molomo Vas da izaberete vlasnika pre prikazivanja detalja! ", "Poruka", JOptionPane.OK_OPTION);
        } else if (pretraga != null) {
            //n.promeniSignal();
            Vlasnik v = pretraga.get(tblVlasnici.getSelectedRow());
            new KreiranjeVlasnika(FormView.FORM_VIEW_MODE, v, this);

        } else {
            //n.promeniSignal();
            uzmiVlasnike();
            Vlasnik v = vlasnici.get(tblVlasnici.getSelectedRow());
            new KreiranjeVlasnika(FormView.FORM_VIEW_MODE, v, this);

        }
        tblVlasnici.getSelectionModel().clearSelection();
    }//GEN-LAST:event_btnDetaljiActionPerformed

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        strPretraga = txtPretraga.getText().toLowerCase();
        if (!strPretraga.isEmpty()) {
            pretragaVlasnika();
            if (pretraga.size() == 0) {
                JOptionPane.showMessageDialog(this, "Sistem ne može da nađe vlasnika po zadatoj vrednosti.Ne postoji vlasnik sa tim imenom ili prezimenom!");
            } else if (pretraga.size() > 1) {
                System.out.println("forms.PretrazivanjeVlasnika.pretragaVlasnika(), prtraga: " + pretraga);
                tblVlasnici.setModel(new VlasniciTableModel(pretraga));
                JOptionPane.showMessageDialog(this, "Sistem je pronašao više rezultata. Molimo Vas da odaberete nekog od prikazanih vlasnika.");
            } else {
                tblVlasnici.setModel(new VlasniciTableModel(pretraga));
                JOptionPane.showMessageDialog(this, "Sistem je našao vlasnika po zadatoj vrednosti.");

            }
            tblVlasnici.getSelectionModel().clearSelection();
        } else {
            pretraga = null;
            JOptionPane.showMessageDialog(this, "Pre pretrage unesite karaktere za pretragu.");
        }
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        n.promeniSignal();
        n=null;
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pretraga = null;
        txtPretraga.setText("");
        tblVlasnici.setModel(new VlasniciTableModel());
        tblVlasnici.getSelectionModel().clearSelection();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton btnNoviVlasnik;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVlasnici;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables

    private void populateForm() {
        try {
            tblVlasnici.setModel(new VlasniciTableModel());
            n = new NitTabele(tblVlasnici, ModelTabele.VLASNIK_MODEL);
        } catch (Exception ex) {
            Logger.getLogger(PretrazivanjeVlasnika.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    void pretragaVlasnika() {
        uzmiVlasnike();
        pretraga = new ArrayList<>();
        for (Vlasnik v : vlasnici) {
            String imePr = v.getIme().toLowerCase() + " " + v.getPrezime().toLowerCase();

            if (v.getIme().toLowerCase().contains(strPretraga) || v.getPrezime().toLowerCase().contains(strPretraga) || imePr.contains(strPretraga)) {
                pretraga.add(v);
            }
        }

    }

    private void uzmiVlasnike() {
        try {
            vlasnici = Komunikacija.getInstance().UcitajVlasnike();
        } catch (Exception ex) {
            Logger.getLogger(PretrazivanjeVlasnika.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
